# fly.toml app configuration file generated for gemini-backend-clone on 2025-07-17T02:12:02+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gemini-backend-clone'
primary_region = 'sin'

[build]


[http_service]
  internal_port = 8021
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[processes]
  web = "python server.py"
  worker = "python celery_worker.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
