name: Gitleaks Scan

on:
  push:
    branches:
      - "**" # Triggers on push to all branches
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Daily at 4 AM

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
